# Source: kubernetes-external-secrets/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-external-secrets
  namespace: "secret-infra"
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::283747779563:role/JenkinsX-poc-external-secrets-secrets-manager
    meta.helm.sh/release-name: 'kubernetes-external-secrets'
    meta.helm.sh/release-namespace: 'secret-infra'
  labels:
    app.kubernetes.io/name: kubernetes-external-secrets
    helm.sh/chart: kubernetes-external-secrets-8.5.5
    app.kubernetes.io/instance: kubernetes-external-secrets
    app.kubernetes.io/managed-by: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
